# Generated by Django 5.2.8 on 2025-12-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_slug_alter_lesson_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
    ]
