# Generated by Django 5.2.8 on 2025-12-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_glossaryterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_details',
            field=models.JSONField(blank=True, help_text='List of learning points', null=True),
        ),
    ]
