# Generated by Django 5.2.8 on 2025-12-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_learning_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learning_details',
        ),
        migrations.CreateModel(
            name='LearningDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_details', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
