# Generated by Django 5.2.8 on 2025-12-21 11:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_learning_details_learningdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='learningdetail',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
