# Generated by Django 5.2.8 on 2025-12-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_video_url_alter_learningdetail_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='speech',
        ),
    ]
