# Generated by Django 5.2.8 on 2026-01-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_options_lessonprogress_started_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlossaryTerm',
        ),
    ]
