# Generated by Django 6.0.1 on 2026-01-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson']},
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='started_at',
        ),
    ]
