# Generated by Django 5.2.8 on 2025-12-04 15:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
