# Generated by Django 5.2.8 on 2025-12-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_topic_challenge_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['id']},
        ),
    ]
