# Generated by Django 5.2.8 on 2025-12-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='task',
            new_name='challenge',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
    ]
