# Generated by Django 6.0.1 on 2026-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_rename_task_submission_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='starter_code',
            field=models.TextField(blank=True, default='class Solution:\n    def solve(self, args):\n        pass'),
        ),
    ]
