# Generated by Django 6.0.1 on 2026-01-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_challenge_starter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='starter_code',
        ),
    ]
