# Generated by Django 6.0.1 on 2026-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_savedchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='time_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
