# Generated by Django 6.0.1 on 2026-03-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_challenge_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge0_id', models.IntegerField(help_text='Judge0 API dagi til ID raqami', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('monaco_identifier', models.CharField(help_text='Monaco Editor uchun til nomi, masalan: python, javascript, cpp', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Sekundlarda', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used',
            field=models.IntegerField(blank=True, help_text='KB da', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('internal_error', 'Internal Error')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.programminglanguage'),
        ),
    ]
