# Generated by Django 6.0.1 on 2026-03-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_programminglanguage_submission_execution_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='difficulty',
        ),
    ]
