# Generated by Django 5.2.8 on 2026-01-03 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('definition', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.DeleteModel(
            name='GlossaryTerm',
        ),
    ]
