# Generated by Django 5.2.8 on 2026-01-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_term_delete_glossaryterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='short_definition',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
