# Generated by Django 6.0.1 on 2026-02-01 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_topic_alter_term_options_term_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
