# Generated by Django 6.0.1 on 2026-02-15 14:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_alter_term_options_savedterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='definition_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='definition_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='definition_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='short_definition_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='short_definition_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='short_definition_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term_uz',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
